In [3]:
import numpy as np
x=np.array([1,2,3,4,5])
print(x)
print(type(x))

[1 2 3 4 5]
<class 'numpy.ndarray'>


In [4]:
y=[1,2,3,4]
print(y)
print(type(y))

[1, 2, 3, 4]
<class 'list'>


In [1]:
import numpy as np
print(np.__version__)

1.22.4


In [2]:
#0 DimDimension Array
a=np.array(10)
print(a)

10


In [9]:
#1-D Array
import numpy as np
b=np.array([10,20])
print(b)
b[1]

[10 20]


20

In [10]:
#2-D Array
import numpy as np
a=np.array([[10,20],[30,40]])
print(a)
a[1][1]

[[10 20]
 [30 40]]


40

In [13]:
#3-D Array
import numpy as np
a=np.array([[[10,20,30,40,50],[60,70,80,90,100],[110,120,130,140,150]]])
print(a)

[[[ 10  20  30  40  50]
  [ 60  70  80  90 100]
  [110 120 130 140 150]]]


In [15]:
#Collection of 2-D
import numpy as np
c=np.array([[[10,20],[30,40]],[[50,60],[70,80]]])
print(type(c))
print(c)

<class 'numpy.ndarray'>
[[[10 20]
  [30 40]]

 [[50 60]
  [70 80]]]


In [20]:
a[0][1][0]

60

SyntaxError: invalid syntax (<ipython-input-18-5289d7adf5e2>, line 1)

In [21]:
print(c[0][1][0])

30


In [22]:
print(c[1][1][1])

80


In [24]:
import numpy as np
b=np.array([[10,20],[30,40]])
for i in b:
    print(i)

[10 20]
[30 40]


In [25]:
print(b)

[[10 20]
 [30 40]]


In [31]:
c=np.nditer(b,order="F")
d=np.nditer(b,order="C")
for i in c:
    print(i)
for j in d:
    print(j)

10
30
20
40
10
20
30
40


In [32]:
import numpy as np
a=np.zeros(2)
print(a)

[0. 0.]


In [35]:
b=np.zeros([2,3])

In [36]:
print(b)

[[0. 0. 0.]
 [0. 0. 0.]]


In [37]:
c=np.zeros([3,3,3])
print(c)

[[[0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]]

 [[0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]]

 [[0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]]]


In [39]:
d=np.zeros([2,3,2])
print(d)

[[[0. 0.]
  [0. 0.]
  [0. 0.]]

 [[0. 0.]
  [0. 0.]
  [0. 0.]]]


In [40]:
#Full()
import numpy as np
a=np.full(3,1)
print(a)

[1 1 1]


In [41]:
b=np.full([2,3],4)
print(b)

[[4 4 4]
 [4 4 4]]


In [42]:
c=np.full([3,3,2],"Muni")
print(c)

[[['Muni' 'Muni']
  ['Muni' 'Muni']
  ['Muni' 'Muni']]

 [['Muni' 'Muni']
  ['Muni' 'Muni']
  ['Muni' 'Muni']]

 [['Muni' 'Muni']
  ['Muni' 'Muni']
  ['Muni' 'Muni']]]


In [4]:
import numpy as np
a=np.random.rand(2,3)
print(a)

[[0.04232534 0.63201387 0.66648725]
 [0.34170231 0.51768966 0.31111513]]


In [6]:
b=np.random.rand(2)
print(b)

[0.28158085 0.89829982]


In [7]:
c=np.random.rand(3,2,3)
print(c)

[[[0.9131266  0.55417505 0.73595406]
  [0.29078906 0.35159819 0.02625635]]

 [[0.96768456 0.76163549 0.48373413]
  [0.3214443  0.65482024 0.12102236]]

 [[0.80310682 0.8656408  0.39333646]
  [0.38972908 0.12394812 0.53554576]]]


In [8]:
d=np.random.rand(1,3,3)
print(d)

[[[0.46217895 0.58038698 0.71015093]
  [0.34865561 0.63225177 0.50956904]
  [0.94769589 0.643572   0.08904148]]]


In [10]:
e=np.random.rand(1)
print(e)

[0.3963757]


In [1]:
import numpy as np
a=np.ones(2)
print(a)

[1. 1.]


In [3]:
b=np.ones([2,3])
print(b)

[[1. 1. 1.]
 [1. 1. 1.]]


In [4]:
c=np.ones([2,3,2])
print(c)

[[[1. 1.]
  [1. 1.]
  [1. 1.]]

 [[1. 1.]
  [1. 1.]
  [1. 1.]]]


In [1]:
import numpy as np
s=np.arange(1,10,2)
print(s)

[1 3 5 7 9]


In [4]:
p=np.arange(0,10,2)
print(p)

[0 2 4 6 8]


In [5]:
v=np.arange(1,100,10)
print(v)

[ 1 11 21 31 41 51 61 71 81 91]


In [11]:
w=np.arange(0,100,10,dtype=float)
print(w)
a=w.reshape(2,5)
print(a)
b=w.reshape(1,10)
print(b)
c=w.reshape(10,1)
print(c)

[ 0. 10. 20. 30. 40. 50. 60. 70. 80. 90.]
[[ 0. 10. 20. 30. 40.]
 [50. 60. 70. 80. 90.]]
[[ 0. 10. 20. 30. 40. 50. 60. 70. 80. 90.]]
[[ 0.]
 [10.]
 [20.]
 [30.]
 [40.]
 [50.]
 [60.]
 [70.]
 [80.]
 [90.]]


In [18]:
import numpy as np
a=np.linspace(10,100,10,endpoint=True,retstep=True,dtype=float)
print(a)
#retstep is false it doesn't show the between intervals 

(array([ 10.,  20.,  30.,  40.,  50.,  60.,  70.,  80.,  90., 100.]), 10.0)


In [21]:
import numpy as np
a=np.logspace(1,10,10,base=2)
print(a)

[   2.    4.    8.   16.   32.   64.  128.  256.  512. 1024.]


In [3]:
import numpy as np
a=np.array([2,3])
print(a)
print(np.size(a))

[2 3]
2


In [7]:
b=np.arange(1,10,2)
print(b)
a=np.size(b)
c=np.shape(b)
print(a)
print(c)

[1 3 5 7 9]
5
(5,)


In [ ]:
#Array Operations 

In [14]:
import numpy as np
a=np.array([[1,2,3,4,5],[0,9,8,7,6]])
print(a)
b=a[0][1]
c=a[1][2]
d=a[1][4]
e=a[1][0]
print(b)
print(c)
print(d)
print(e)


[[1 2 3 4 5]
 [0 9 8 7 6]]
2
8
6
0


In [18]:
b=np.array([[[1,2,3,4,5]
             [6,7,8,9,10],
             [11,12,13,14,15]]])
print(type(b))
print(b)

<class 'numpy.ndarray'>
[[[ 1  2  3  4  5]
  [ 6  7  8  9 10]
  [11 12 13 14 15]]]


IndexError: index 1 is out of bounds for axis 0 with size 1

In [22]:
#Slicing
import numpy as np
a=np.linspace(10,100,10,endpoint=True)
print(a)
a[2:6]

[ 10.  20.  30.  40.  50.  60.  70.  80.  90. 100.]


array([30., 40., 50., 60.])

In [24]:
#Copy()
import numpy as np
a=np.array([10,20,30,40,50,60])
print(a)
b=np.copy(a)


[10 20 30 40 50 60]


In [25]:
b

array([10, 20, 30, 40, 50, 60])

In [26]:
a
b

array([10, 20, 30, 40, 50, 60])

In [27]:
print(a)
print(b)

[10 20 30 40 50 60]
[10 20 30 40 50 60]


In [30]:
import numpy as np
a=np.array([[10,20,30,40,50],
           [60,70,80,90,100]])
print(a)
c=np.copy(a)
print(c)

[[ 10  20  30  40  50]
 [ 60  70  80  90 100]]
[[ 10  20  30  40  50]
 [ 60  70  80  90 100]]


In [31]:
print(a)
print(c)

[[ 10  20  30  40  50]
 [ 60  70  80  90 100]]
[[ 10  20  30  40  50]
 [ 60  70  80  90 100]]


In [32]:
import numpy as np
a=np.array([[10,20,30,40,50],
            [60,70,80,90,100]])
print(a)

[[ 10  20  30  40  50]
 [ 60  70  80  90 100]]


In [33]:
b=np.copy(a)
print(b)

[[ 10  20  30  40  50]
 [ 60  70  80  90 100]]


In [35]:
a[0][1]=100
print(a)
print(b)

[[ 10 100  30  40  50]
 [ 60  70  80  90 100]]
[[ 10  20  30  40  50]
 [ 60  70  80  90 100]]


In [43]:
c=b.view()
b[0][1]=200
print(b)
print(c)

[[ 10 200  30  40  50]
 [ 60  70  80  90 100]]
[[ 10 200  30  40  50]
 [ 60  70  80  90 100]]


In [44]:
import numpy as np
a=np.array([3,1,7,9,2,5,0,8,7,10,34,11,44,67,43])
srt=np.sort(a)
print(srt)

[ 0  1  2  3  5  7  7  8  9 10 11 34 43 44 67]


In [46]:
b=np.array([[1,5,2],
           [10,56,23],
           [34,21,89]])
print(b)

[[ 1  5  2]
 [10 56 23]
 [34 21 89]]


In [48]:
srt1=np.sort(b,axis=0)
print(srt1)

[[ 1  5  2]
 [10 21 23]
 [34 56 89]]


In [49]:
srt2=np.sort(b,axis=1)
print(srt2)

[[ 1  2  5]
 [10 23 56]
 [21 34 89]]


In [53]:
#Append
import numpy as np
a=np.array([10,20,30,40,5,60])
print(a)
b=np.append(a,80)
print(b)

[10 20 30 40  5 60]
[10 20 30 40  5 60 80]


In [59]:
c=np.array([[1,2,3],
             [4,5,6]])
print(c)
d=np.append(c,[[10,11,13]],axis=0)
print(d)

[[1 2 3]
 [4 5 6]]
[[ 1  2  3]
 [ 4  5  6]
 [10 11 13]]


In [63]:
e=np.array([[10,20],[30,40]])
f=np.array([[50,60],[70,80]])
print(e)
print(f)
np.append(e,f).reshape(4,2)

[[10 20]
 [30 40]]
[[50 60]
 [70 80]]


array([[10, 20],
       [30, 40],
       [50, 60],
       [70, 80]])

In [65]:
#Index
import numpy as np
a=np.array([10,20,30,40,50,60])
print(a)
b=np.insert(a,2,100)
print(b)

[10 20 30 40 50 60]
[ 10  20 100  30  40  50  60]


In [74]:
c=np.array([[10,20,30],
            [40,50,60]])
print(c)
d=np.insert(c,2,[[70,80,90]],axis=0)
print(d)

[[10 20 30]
 [40 50 60]]
[[10 20 30]
 [40 50 60]
 [70 80 90]]


In [75]:
#Delete
import numpy as np
a=np.array([10,20,30,40,50,60,70])
print(a)
b=np.delete(a,3)
print(b)

[10 20 30 40 50 60 70]
[10 20 30 50 60 70]


In [76]:
import numpy as np
c=np.array([[1,2,3],
            [4,5,6],
            [7,8,9]])
print(c)
d=np.delete(c,1,axis=0)
print(d)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[1 2 3]
 [7 8 9]]


In [3]:
#Concatination
import numpy as np
a=np.array([[1,2,3,4,5],
            [6,7,8,9,10]])
b=np.array([[11,12,13,14,15],
            [16,17,18,19,20]])
print(a)
print(b)
c=np.concatenate((a,b))
print(c)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]
[[11 12 13 14 15]
 [16 17 18 19 20]]
[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]]


In [4]:
c[0]

array([1, 2, 3, 4, 5])

In [5]:
c[1]

array([ 6,  7,  8,  9, 10])

In [6]:
c[1][2]

8

In [7]:
c[4]

IndexError: index 4 is out of bounds for axis 0 with size 4

In [8]:
c[3]

array([16, 17, 18, 19, 20])

In [9]:
c[3][4]

20

In [7]:
#Split
import numpy as np
a=np.array([1,2,3,4,5,6,7,8,9,10])
print(a)
b=np.split(a,5)
print(b)
c=np.split(a,2)
print(c)
d=np.split(a,[3,5])
print(d)

[ 1  2  3  4  5  6  7  8  9 10]
[array([1, 2]), array([3, 4]), array([5, 6]), array([7, 8]), array([ 9, 10])]
[array([1, 2, 3, 4, 5]), array([ 6,  7,  8,  9, 10])]
[array([1, 2, 3]), array([4, 5]), array([ 6,  7,  8,  9, 10])]


In [9]:
#Split 2-D
import numpy as np
a=np.array([[1,2,3],
            [4,5,6],
            [7,8,9]])
print(a)
b=np.split(a,3,axis=0)
print(b)
c=np.split(a,3,axis=1)
print(c)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[array([[1, 2, 3]]), array([[4, 5, 6]]), array([[7, 8, 9]])]
[array([[1],
       [4],
       [7]]), array([[2],
       [5],
       [8]]), array([[3],
       [6],
       [9]])]


In [13]:
#Where
import numpy as np
a=np.arange(0,100,10).reshape(2,5)
print(a)
b=np.where(a==20)
print(b)
c=np.where(a%6==0)
print(c)

[[ 0 10 20 30 40]
 [50 60 70 80 90]]
(array([0], dtype=int64), array([2], dtype=int64))
(array([0, 0, 1, 1], dtype=int64), array([0, 3, 1, 4], dtype=int64))


In [14]:
import numpy as np
a=np.array([10,20,30,40,50,60])
print(a)
b=np.where(a==30)
print(b)

[10 20 30 40 50 60]
(array([2], dtype=int64),)


In [8]:
#Searchsorted
import numpy as np
a=np.arange(0,10,1)
print(a)
b=np.searchsorted(a,3)
print(b)
c=np.searchsorted(a,[4,8])
print(c)

[0 1 2 3 4 5 6 7 8 9]
3
[4 8]
